version: '3'

services:
  global-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=globalfundingdb
